# Base
#
# VERSION               0.0.1

FROM       centos
MAINTAINER Puneet Goyal "puneet@codeignition.co"

RUN wget https://opscode-omnibus-packages.s3.amazonaws.com/el/6/x86_64/chef-server-11.0.8-1.el6.x86_64.rpm
RUN yum install chef-server-11.0.8-1.el6.x86_64.rpm -y

